// Code generated by "stringer -type=FrameVbrMode"; DO NOT EDIT.

package mpg123

import "fmt"

const _FrameVbrMode_name = "CbrVbrAbr"

var _FrameVbrMode_index = [...]uint8{0, 3, 6, 9}

func (i FrameVbrMode) String() string {
	if i < 0 || i >= FrameVbrMode(len(_FrameVbrMode_index)-1) {
		return fmt.Sprintf("FrameVbrMode(%d)", i)
	}
	return _FrameVbrMode_name[_FrameVbrMode_index[i]:_FrameVbrMode_index[i+1]]
}
