// Code generated by "stringer -type=MpegVersion"; DO NOT EDIT.

package mpg123

import "fmt"

const _MpegVersion_name = "Mpeg10Mpeg20Mpeg25"

var _MpegVersion_index = [...]uint8{0, 6, 12, 18}

func (i MpegVersion) String() string {
	if i < 0 || i >= MpegVersion(len(_MpegVersion_index)-1) {
		return fmt.Sprintf("MpegVersion(%d)", i)
	}
	return _MpegVersion_name[_MpegVersion_index[i]:_MpegVersion_index[i+1]]
}
